version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: succeshub-postgres
    environment:
      POSTGRES_DB: succeshub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./02-init-keycloak-db.sh:/docker-entrypoint-initdb.d/02-init-keycloak-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: succeshub-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HTTP_PORT: 8080
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/succeshub-realm-realm.json
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-export/succeshub-realm-realm.json:/opt/keycloak/data/import/succeshub-realm-realm.json
    command: ["start-dev", "--import-realm"]
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: succeshub-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres-data: